from django.db import models
from django.contrib.auth.models import User
# from django.conf import settings

'''
Models for label_game app

models we will need:

user: ID, name, profile picture, etc (built in)
image: image ID, classification, source, source_user, date, filename
user label: image, user, label
total votes: for each image, label - number of votes
'''

# Create your models here.


class Image(models.Model):
    """ A database record for uploaded images to be labeled """
    source = models.CharField("image source: web, sift generator func, camera",
                              max_length=512, default=None, null=True)
    correct_label = models.IntegerField("Correct label; 0=simulated, 1=image")
    google_labels = models.CharField("Labels generated by google vision API",
                                     max_length=512, default=None, null=True)
    tweeted = models.BooleanField("Image was tweeted", default=False)
    uploaded_by = models.ForeignKey(User, default=None, null=True)
    filename = models.FileField("file path", upload_to='images')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'img: class={}, source={}, file={}'.format(self.correct_label,
                                                          self.source,
                                                          self.filename)


class Choice(models.Model):
    """ possible choices for labels, w/ explanatory text """
    choice = models.IntegerField()
    alt_text = models.CharField("text explaining what integer label means",
                                max_length=64)

    def __str__(self):
        return "choice: int {} means {}".format(self.choice, self.alt_text)


class TotalVotes(models.Model):
    """ Aggregated votes (by all users) for an individual Image """
    image = models.ForeignKey(Image)
    choice = models.ForeignKey(Choice)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return "{} -  has {} votes for label {}".format(str(self.image),
                                                        str(self.votes),
                                                        str(self.choice))
