# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField()),
                ('alt_text', models.CharField(max_length=64, verbose_name='text explaining what integer label means')),
            ],
        ),
        migrations.RemoveField(
            model_name='userlabel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userlabel',
            name='user',
        ),
        migrations.AddField(
            model_name='image',
            name='google_labels',
            field=models.CharField(default=None, max_length=512, null=True, verbose_name='Labels generated by google vision API'),
        ),
        migrations.AddField(
            model_name='image',
            name='tweeted',
            field=models.BooleanField(default=False, verbose_name='Image was tweeted'),
        ),
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.FileField(upload_to='', verbose_name='file path'),
        ),
        migrations.AlterField(
            model_name='totalvotes',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeller.Choice'),
        ),
        migrations.DeleteModel(
            name='UserLabel',
        ),
    ]
