# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0002_auto_20170829_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalvotes',
            old_name='label',
            new_name='choice',
        ),
    ]
