# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0004_auto_20170830_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='google_labels',
            new_name='description',
        ),
        migrations.AddField(
            model_name='image',
            name='google_raw_data',
            field=jsonfield.fields.JSONField(null=True, verbose_name='google cloud vision API - JSON'),
        ),
        migrations.AddField(
            model_name='image',
            name='sift_label',
            field=models.IntegerField(null=True, verbose_name='SIFT-generated label; 0=sim, 1=image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tweeted',
            field=models.BooleanField(default=False, verbose_name='Image was tweeted?'),
        ),
    ]
